Repository ThugMS/GameLab_W02, pull requests merged in 2023-08, with the labels that each got.

#1 [Feat] : 폴더 생성
  Assets/Prefabs.meta
  Assets/Resoures.meta
  Assets/Resoures/Prefabs.meta
  Assets/Scenes/MSTest.unity
  Assets/Scenes/MSTest.unity.meta
  Assets/Scenes/Main.unity
  Assets/Scenes/Main.unity.meta
  Assets/Scripts.meta
  Assets/Scripts/Character.meta
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Character/CharacterMovement.cs.meta
  ProjectSettings/SceneTemplateSettings.json
Labels: Feat, minseok

#2 [Feat] : Input System 액션 추가, 회전 구현
  Assets/InputSystem.meta
  Assets/InputSystem/CharacterAction.inputactions
  Assets/InputSystem/CharacterAction.inputactions.meta
  Assets/Materials.meta
  Assets/Materials/Black.mat
  Assets/Materials/Black.mat.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Character/CharacterMovement.cs
  ProjectSettings/ProjectSettings.asset
Labels: Feat, minseok

#3 [Feat] : 캐릭터의 기본 회전 이동 구현
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Character/CharacterMovement.cs
Labels: Feat, minseok

#8 merged from main
  Assets/Materials/Colors.meta
  Assets/Materials/Colors/GroundBrown.mat
  Assets/Materials/Colors/GroundBrown.mat.meta
  Assets/Scenes/SHTest.unity
  Assets/Scenes/SHTest.unity.meta
  Assets/Scripts/Character/CharacterJump.cs
  Assets/Scripts/Character/CharacterJump.cs.meta
  Assets/Seunghoon_Temporary.meta
  Assets/Seunghoon_Temporary/Player.inputactions
  Assets/Seunghoon_Temporary/Player.inputactions.meta
  Assets/Seunghoon_Temporary/TestMover.cs
  Assets/Seunghoon_Temporary/TestMover.cs.meta
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
  ProjectSettings/TimelineSettings.asset
Labels: enhancement, Feat, seungHoon

#9 [Fix] : 플레이어 점프 스크립트 수정
  Assets/InputSystem/CharacterAction.inputactions
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Character/CharacterDash.cs
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/JHTest/JHDash.cs
  Assets/Scripts/Managers/CharacterManager.cs
Labels: Fix, minseok

#10 [Fix] : 점프 버그 발견 수정요청
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Character/CharacterMovement.cs
Labels: Fix, minseok, seungHoon

#11 [Fixed] : 빠르게 더블점프 시 점프가 너무 강하게 발생하던 문제 수정
  Assets/Materials/Wine.mat
  Assets/Materials/Wine.mat.meta
  Assets/Prefabs/Managers.meta
  Assets/Prefabs/Managers/CharacterManager.prefab
  Assets/Prefabs/Managers/CharacterManager.prefab.meta
  Assets/Prefabs/Managers/Input Manager.prefab
  Assets/Prefabs/Managers/Input Manager.prefab.meta
  Assets/Prefabs/Player.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Player/Player.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scenes/SHTest.unity
  Assets/Scripts/Character/CharacterJump.cs
Labels: bug, Fix, seungHoon

#15 [Feat] : 프로젝터 추가
  Assets/Materials/Projectors.meta
  Assets/Materials/Projectors/Guidelines.txt
  Assets/Materials/Projectors/Guidelines.txt.meta
  Assets/Materials/Projectors/Materials.meta
  Assets/Materials/Projectors/Materials/RedZoneProjector.mat
  Assets/Materials/Projectors/Materials/RedZoneProjector.mat.meta
  Assets/Materials/Projectors/Shaders.meta
  Assets/Materials/Projectors/Shaders/RedZone.shader
  Assets/Materials/Projectors/Shaders/RedZone.shader.meta
  Assets/Materials/Projectors/Textures.meta
  Assets/Materials/Projectors/Textures/Falloff.psd
  Assets/Materials/Projectors/Textures/Falloff.psd.meta
  Assets/Materials/Projectors/Textures/Red_Circle.png
  Assets/Materials/Projectors/Textures/Red_Circle.png.meta
  Assets/Materials/Projectors/Textures/Red_Rectangle.png
  Assets/Materials/Projectors/Textures/Red_Rectangle.png.meta
  Assets/Scenes/JHTest.unity
  ProjectSettings/TagManager.asset
Labels: Feat, jhoohyung

#16 [Feat] : 카메라 시점과 플레이어의 시점 분리
  Assets/CinemachineBlenderSettings.asset
  Assets/CinemachineBlenderSettings.asset.meta
  Assets/InputSystem.inputsettings.asset
  Assets/InputSystem.inputsettings.asset.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/CameraController.cs
  Assets/Scripts/CameraController.cs.meta
  Assets/Scripts/Character/CharacterDash.cs
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Character/TrackingPlayer.cs
  Assets/Scripts/Character/TrackingPlayer.cs.meta
  Assets/Scripts/Managers/CharacterManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: Feat, minseok

#19 [Feat] : GameManager 트리거 완성
  Assets/Prefabs/Cameras/BackViewVcam.prefab
  Assets/Prefabs/Cameras/BackViewVcam.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/BossStageTrigger.cs
  Assets/Scripts/BossStageTrigger.cs.meta
  Assets/Scripts/Character/CharacterDash.cs
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Managers/CharacterManager.cs
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/GameManager.cs.meta
Labels: Feat, minseok, seungHoon

#21 [Feat] : 보스 스프라이트 추가, 카메라 수정 스크립트 추가
  Assets/Animation.meta
  Assets/Animation/Boss.controller
  Assets/Animation/Boss.controller.meta
  Assets/Animation/BossIdle.anim
  Assets/Animation/BossIdle.anim.meta
  Assets/Prefabs/Boss.prefab
  Assets/Prefabs/Boss.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Managers/CharacterManager.cs
Labels: Feat, minseok

#24 [Fix] : 점프시 연속대쉬제거
  Assets/Scripts/Character/CharacterDash.cs
Labels: Fix, jhoohyung

#27 [Faet] : Obstacle 더미 추가
  Assets/Materials/GridBase_Ground.mat
  Assets/Materials/GridBase_Ground.mat.meta
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_1.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_1.prefab.meta
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_2.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_2.prefab.meta
  Assets/Scenes/JHTest.unity
  Assets/Scripts/Obstacles/FallingObstacleSpawner.cs
Labels: Feat, jhoohyung

#28 [Feat] : 보스 공격 페이즈1 추가
  Assets/Animation/BossIdle.anim
  Assets/Materials/Colors/Red.mat
  Assets/Materials/Colors/Red.mat.meta
  Assets/Prefabs/Boss.prefab
  Assets/Prefabs/BossObstacleBlack.prefab
  Assets/Prefabs/BossObstacleBlack.prefab.meta
  Assets/Prefabs/BossObstacleRed.prefab
  Assets/Prefabs/BossObstacleRed.prefab.meta
  Assets/Resources.meta
  Assets/Resources/Prefabs.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Boss.meta
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Boss/Boss.cs.meta
  Assets/Scripts/BossBlackObstacle.cs
  Assets/Scripts/BossBlackObstacle.cs.meta
  Assets/Scripts/BossRedObstacle.cs
  Assets/Scripts/BossRedObstacle.cs.meta
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Managers/CharacterManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: Feat, Fix, minseok

#29 [Feat] : 보스 1차 기믹 반복하는 코드 추가
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Boss/Boss.cs
Labels: Feat, minseok

#34 [Feat] : 보스 스테이지 프리팹추가 및 콜라이더 추가
  Assets/Prefabs/Boss.prefab
  Assets/Prefabs/BossStage.prefab
  Assets/Prefabs/BossStage.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Character/CharacterDash.cs
Labels: Feat, minseok

#35 [Feat] : Main 씬 병합
  Assets/Prefabs/DashStage.prefab
  Assets/Prefabs/Managers/GameManager.prefab
  Assets/Prefabs/Managers/GameManager.prefab.meta
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Prefabs/Player/MainPlayer.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scenes/Main.unity
  Assets/Scenes/MainJH.unity
  Assets/Scenes/MainJH.unity.meta
  Assets/Scenes/MainMS.unity
  Assets/Scenes/MainMS.unity.meta
  Assets/Scenes/MainSH.unity
  Assets/Scenes/MainSH.unity.meta
Labels: Feat, minseok

#36 [Feat] : DashStage 레벨, 카메라존 수정
  Assets/Materials/GridBase_Step.mat
  Assets/Materials/GridBase_Step.mat.meta
  Assets/Prefabs/DashStage.prefab
  Assets/Scenes/MainJH.unity
  Assets/Scripts/Camera/CameraRayAplha.cs
Labels: Feat, jhoohyung

#37 [Fix] : 캐릭터 움직임 없을 시 혼자 회전하는 오류 수정
  Assets/InputSystem.inputsettings.asset
  Assets/InputSystem/CharacterAction.inputactions
  Assets/Scenes/MainMS.unity
  Assets/Scripts/Character/CharacterJump.cs
  Assets/Scripts/Character/CharacterMovement.cs
Labels: Fix, minseok

#39 [Feat] : 데드 라인 세이브 포인트 추가
  Assets/Prefabs/BossStage.prefab
  Assets/Scenes/MainMS.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Character/CharacterJump.cs
  Assets/Scripts/DeadZone.cs
  Assets/Scripts/DeadZone.cs.meta
  Assets/Scripts/Managers/CharacterManager.cs
  Assets/Scripts/SetRespawnTrigger.cs
  Assets/Scripts/SetRespawnTrigger.cs.meta
Labels: Feat, Fix

#41 [Feat] : 보스패턴 추가
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15_B.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15_B.prefab.meta
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x85_B.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x85_B.prefab.meta
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_7.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_7.prefab.meta
  Assets/Prefabs/Save_SpownPoint.prefab
  Assets/Prefabs/Save_SpownPoint.prefab.meta
  Assets/Prefabs/UI_WorldSpace.prefab
  Assets/Prefabs/UI_WorldSpace.prefab.meta
  Assets/Scenes/MainJH.unity
  Assets/Scripts/Obstacles/FallingObstacleBoss.cs
  Assets/Scripts/Obstacles/FallingObstacleBoss.cs.meta
Labels: Feat, jhoohyung

#45 [Feat] : 날아가는 싱크 맞게 Fixed 타임으로 수정 및 장애물 삭제 추가
  Assets/Prefabs/BossObstacleBlack.prefab
  Assets/Prefabs/BossObstacleRed.prefab
  Assets/Prefabs/BossStage.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/BossBlackObstacle.cs
  Assets/Scripts/BossFenceCollider.cs
  Assets/Scripts/BossFenceCollider.cs.meta
  Assets/Scripts/BossRedObstacle.cs
  Assets/Scripts/BossStopTrigger.cs
  Assets/Scripts/BossStopTrigger.cs.meta
  Assets/Scripts/Managers/BossManager.cs
  Assets/Scripts/Managers/BossManager.cs.meta
  Assets/Scripts/Obstacles/SuperJumpStep.cs
  ProjectSettings/TagManager.asset
Labels: Feat, minseok

#46 [Feat] : 보스 패턴 시작 트리거 생성
  Assets/Prefabs/BossStage.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Boss/BossBlackObstacle.cs
  Assets/Scripts/Boss/BossBlackObstacle.cs.meta
  Assets/Scripts/Boss/BossFenceCollider.cs
  Assets/Scripts/Boss/BossFenceCollider.cs.meta
  Assets/Scripts/Boss/BossPhaseTrigger.cs
  Assets/Scripts/Boss/BossPhaseTrigger.cs.meta
  Assets/Scripts/Boss/BossRedObstacle.cs
  Assets/Scripts/Boss/BossRedObstacle.cs.meta
  Assets/Scripts/Boss/BossStageTrigger.cs
  Assets/Scripts/Boss/BossStageTrigger.cs.meta
  Assets/Scripts/Boss/BossStopTrigger.cs
  Assets/Scripts/Boss/BossStopTrigger.cs.meta
  Assets/Scripts/Managers/BossManager.cs
  Assets/Tree.prefab
  Assets/Tree.prefab.meta
  Assets/Tree_Textures.meta
  Assets/Tree_Textures/diffuse.png
  Assets/Tree_Textures/diffuse.png.meta
  Assets/Tree_Textures/normal_specular.png
  Assets/Tree_Textures/normal_specular.png.meta
  Assets/Tree_Textures/shadow.png
  Assets/Tree_Textures/shadow.png.meta
  Assets/Tree_Textures/translucency_gloss.png
  Assets/Tree_Textures/translucency_gloss.png.meta
Labels: Feat, minseok

#54 [Feat] : ViewRot UI 추가
  Assets/Images.meta
  Assets/Images/CMRot.png
  Assets/Images/CMRot.png.meta
  Assets/Prefabs/UI_HUD.prefab
  Assets/Prefabs/UI_HUD.prefab.meta
  Assets/Scenes/MainJH.unity
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: Feat, jhoohyung

#56 [Feat] : 메인 씬 병합 완료
  Assets/Prefabs/BossObstacleBlack.prefab
  Assets/Prefabs/BossObstacleRed.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Boss/BossBlackObstacle.cs
  Assets/Scripts/Boss/BossCharge.cs
  Assets/Scripts/Boss/BossCharge.cs.meta
  Assets/Scripts/Boss/BossRedObstacle.cs
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Managers/BossManager.cs
  ProjectSettings/DynamicsManager.asset
Labels: Feat, minseok

#61 [Feat] : 시작, 클리어씬 추가
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_8.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_8.prefab.meta
  Assets/Prefabs/UI_WorldSpace.prefab
  Assets/Scenes/ClearScene.unity
  Assets/Scenes/ClearScene.unity.meta
  Assets/Scenes/MainJH.unity
  Assets/Scenes/StartScene.unity
  Assets/Scenes/StartScene.unity.meta
  Assets/Scripts/SceneLoader.cs
  Assets/Scripts/SceneLoader.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Labels: Feat, jhoohyung

#62 [Feat] : 보스 페이즈1 완성
  Assets/Prefabs/Managers/BossManager.prefab
  Assets/Prefabs/Managers/BossManager.prefab.meta
  Assets/Scripts/Boss/BossEnablePhaseTrigger.cs
  Assets/Scripts/Boss/BossEnablePhaseTrigger.cs.meta
  ProjectSettings/DynamicsManager.asset
Labels: Feat, minseok

#64 [Fix] : BossManager 스크립트 수정
  Assets/Prefabs/BossStage.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Boss/BossCharge.cs
  Assets/Scripts/Boss/BossRedObstacle.cs
  Assets/Scripts/Managers/BossManager.cs
Labels: Fix, minseok

#65 [Feat] : 플레이어 움직임 스턴 모션과 동기화 추가
  Assets/Scenes/MSTest.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Character/CharacterDash.cs
  Assets/Scripts/Character/CharacterJump.cs
Labels: Feat, minseok

#66 [Feat] : 플레이어 회사원 컨셉 추가
  Assets/Materials/Colors/BagColor.mat
  Assets/Materials/Colors/BagColor.mat.meta
  Assets/Prefabs/Player/MainPlayer.prefab
Labels: Feat, minseok

#69 [Feat] : 장애물 프리팹 추가
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_100x100.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_100x100.prefab.meta
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x100.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x100.prefab.meta
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_5x100.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_5x100.prefab.meta
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_Circle.prefab
  Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_Circle.prefab.meta
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_10.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_10.prefab.meta
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_11.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_11.prefab.meta
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_12.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_12.prefab.meta
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_9.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_9.prefab.meta
  Assets/Scenes/JHBossTest.unity
  Assets/Scenes/JHBossTest.unity.meta
  Assets/Scenes/MainJH.unity
  Assets/Scripts/Obstacles/FallingObstacleBossManager.cs
  Assets/Scripts/Obstacles/FallingObstacleBossManager.cs.meta
  Assets/Scripts/Obstacles/FallingObstacleSpawner_RD.cs
  Assets/Scripts/Obstacles/FallingObstacleSpawner_RD.cs.meta
Labels: Feat, jhoohyung

#70 [Fix] : Obstacle랜덤생성 수정
  Assets/Scenes/JHBossTest.unity
  Assets/Scripts/Obstacles/FallingObstacleBossManager.cs
  Assets/Scripts/Obstacles/FallingObstacleSpawner_RD.cs
Labels: Fix, jhoohyung

#71 [Feat] : 게임패드 마우스 입력 구분해서 카메라 감도 조절추가
  Assets/Scripts/Character/CharacterMovement.cs
Labels: Feat, minseok

#72 Minseok
  Assets/Prefabs/BossStage.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/FallingObstacleBossManager.prefab
  Assets/Prefabs/Obstacle/ObstacleSpawner/FallingObstacleBossManager.prefab.meta
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Boss/BossKidSpawner.cs
  Assets/Scripts/Boss/BossPhase2.cs
  Assets/Scripts/Boss/BossPhase2.cs.meta
  Assets/Scripts/Boss/BossTongnamuSpawner.cs
Labels: Feat, minseok, seungHoon, jhoohyung

#75 [Feat] : 페이즈 2 카메라 제작, 쪼꼬미 Layer Obstacle화
  Assets/CameraBlends/CameraBlendTest.asset
  Assets/Prefabs/Boss/PlayerChaser.prefab
  Assets/Prefabs/Cameras/BossPhase2Cam.prefab
  Assets/Prefabs/Cameras/BossPhase2Cam.prefab.meta
  Assets/Prefabs/Cameras/ZoneVcams/BossCamera.prefab
  Assets/Prefabs/Cameras/ZoneVcams/BossCamera.prefab.meta
  Assets/Scenes/SH/MainSH_Temp.unity
  Assets/Scenes/SH/MainSH_Temp.unity.meta
  Assets/Scripts/Boss/BossPhase2.cs
Labels: enhancement, Feat, minseok, seungHoon, jhoohyung

#76 [Feat] : 쪼꼬미 맞으면 튀어오름
  Assets/Prefabs/Boss/PlayerChaser.prefab
  Assets/Scenes/SH/MainSH_Temp.unity
  Assets/Scripts/Projectiles/PlayerChaser.cs
  Assets/Scripts/Projectiles/TongnamuAddForcer.cs
Labels: Feat, seungHoon

#77 [Fix] : ObstacleSpawner, savePoint 위치변경
  Assets/Prefabs/DashStage.prefab
  Assets/Prefabs/Save_SpownPoint.prefab
Labels: Fix, jhoohyung

#79 [Fix] : 넥타이 선글라스에 충돌판정 수정
  Assets/Prefabs/Boss.prefab
  Assets/Prefabs/BossStage.prefab
  Assets/Prefabs/Cameras/BossPhase2Cam.prefab
  Assets/Prefabs/Player/MainPlayer.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scenes/MainSH.unity
  Assets/Scenes/SH/MainSH_Temp.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Boss/BossBlackObstacle.cs
  Assets/Scripts/Boss/BossPhase2.cs
  Assets/Scripts/Boss/BossRedObstacle.cs
  Assets/Scripts/Character/CharacterDash.cs
  Assets/Scripts/Character/CharacterMovement.cs
  Assets/Scripts/Managers/BossManager.cs
  Assets/Scripts/Managers/CharacterManager.cs
Labels: Fix, minseok

#80 [Feat] : 밸런스 패치와 버튼 추가
  Assets/Prefabs/BossStage 1.prefab
  Assets/Prefabs/BossStage 1.prefab.meta
  Assets/Prefabs/PhaseStarter.prefab
  Assets/Prefabs/PhaseStarter.prefab.meta
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Managers/CharacterManager.cs
Labels: Feat, minseok

#81 [Fix] : 보스 장애물 리스폰 위치 수정
  Assets/Scripts/Obstacles/FallingObstacle_B.cs
Labels: Fix, jhoohyung

#82 [Fix] : 보스 기믹 밸런스 조절 완료 엔딩 추가
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Managers/BossManager.cs
  Assets/Scripts/Managers/CharacterManager.cs
Labels: Fix, minseok

#83 [Feat] : 보스 엔딩 추가, 쪼꼬미 얼굴 추가
  Assets/Prefabs/Boss/PlayerChaser.prefab
  Assets/Scripts/Boss/BossPhase2.cs
Labels: Feat, minseok

#84 [Feat] : Map2 대거 수정, [Fix] : 플레이어 죽어도 쪼꼬미 사라지지 않던 버그 수정
  Assets/Prefabs/Maps/Map_SH1.prefab
  Assets/Prefabs/Save_SpownPoint.prefab
  Assets/Prefabs/Stage2.meta
  Assets/Prefabs/Stage2/SimpleBlock.prefab
  Assets/Prefabs/Stage2/SimpleBlock.prefab.meta
  Assets/Prefabs/Stage2/SimpleBlockRed.prefab
  Assets/Prefabs/Stage2/SimpleBlockRed.prefab.meta
  Assets/Prefabs/Stage2/SimpleBlockShooter.prefab
  Assets/Prefabs/Stage2/SimpleBlockShooter.prefab.meta
  Assets/Scenes/SH/MainSH_0828.unity
  Assets/Scenes/SH/MainSH_0828.unity.meta
  Assets/Scripts/Managers/CharacterManager.cs
  Assets/Scripts/Projectiles/PlayerChaser.cs
  Assets/Scripts/Projectiles/ProjectileSpawner.cs
Labels: enhancement, Feat, Fix, seungHoon

#85 [Feat] : 시작,클리어씬 연결
  Assets/Scenes/MainSH.unity
  Assets/Scripts/Managers/BossManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: Feat, jhoohyung

#86 [Feat] : 통나무 맞아도 스턴 안걸리던 문제 해결, Stage2 재배치
  Assets/Prefabs/Boss/Boss_Tongnamu.prefab
  Assets/Prefabs/Maps/Map_SH1.prefab
  Assets/Prefabs/Projectiles/Tongnamu.prefab
  Assets/Scenes/SH/MainSH_0828.unity
  Assets/Scripts/Projectiles/TongnamuAddForcer.cs
Labels: Fix, seungHoon

#87 [Fix] : 시작계단, 보스외벽 수정
  Assets/Prefabs/BossStage 1.prefab
  Assets/Prefabs/DashStage.prefab
Labels: Fix, jhoohyung
